puts "deleting old data"

User.destroy_all
Wardrobe.destroy_all
Item.destroy_all

puts "data deleted"

puts "reseting tables"

ActiveRecord::Base.connection.execute("Delete from items")
ActiveRecord::Base.connection.execute("DELETE FROM SQLIte_SEQUENCE WHERE name='items'")
ActiveRecord::Base.connection.execute("Delete from wardrobes")
ActiveRecord::Base.connection.execute("DELETE FROM SQLIte_SEQUENCE WHERE name='wardrobes'")
ActiveRecord::Base.connection.execute("Delete from users")
ActiveRecord::Base.connection.execute("DELETE FROM SQLIte_SEQUENCE WHERE name='users'")

puts "tables reset"

puts "seeding data"

User.create(name: "Meghann")
User.create(name: "Hyo")
User.create(name: "AJ")
User.create(name: "Jason")
User.create(name: "Andrew")
User.create(name: "Alyssa")
User.create(name: "Varun")
User.create(name: "Valentino")

Wardrobe.create(user_id: 1, name: "Meghann's wardrobe")
Wardrobe.create(user_id: 2, name: "Hyo's wardrobe")
Wardrobe.create(user_id: 3, name: "AJ's wardrobe")
Wardrobe.create(user_id: 4, name: "Jason's wardrobe")
Wardrobe.create(user_id: 5, name: "Andrew's wardrobe")
Wardrobe.create(user_id: 6, name: "Alyssa's wardrobe")
Wardrobe.create(user_id: 7, name: "Varun's wardrobe")
Wardrobe.create(user_id: 8, name: "Valentino's wardrobe")
Wardrobe.create(user_id: 1, name: "Meghann's dressed up wardrobe")
Wardrobe.create(user_id: 2, name: "Hyo's cold weather wardrobe")
Wardrobe.create(user_id: 3, name: "AJ's vacation attire")
Wardrobe.create(user_id: 4, name: "Jason's summer collection")
Wardrobe.create(user_id: 5, name: "Andrew's workout closet")
Wardrobe.create(user_id: 6, name: "Alyssa's trendy outfits")
Wardrobe.create(user_id: 7, name: "Varun's winter collection")
Wardrobe.create(user_id: 8, name: "Valentino's fancy collection")

#Meghann's clothes 
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 1, wardrobe_id: 1)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "shoes", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 1, wardrobe_id: 9)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 1, wardrobe_id: 1)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "shoes", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 1, wardrobe_id: 9)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 1, wardrobe_id: 9)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 1, wardrobe_id: 1)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 1, wardrobe_id: 9)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 1, wardrobe_id: 1)


#Hyo's clothes
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 2, wardrobe_id: 2)
Item.create(kind: "shoes", color: "brown", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 2, wardrobe_id: 2)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 2, wardrobe_id: 10)
Item.create(kind: "shoes", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 2, wardrobe_id: 10)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 2, wardrobe_id: 2)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 2, wardrobe_id: 10)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 2, wardrobe_id: 10)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "green", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "shoes", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 2, wardrobe_id: 10)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 2, wardrobe_id: 10)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 2, wardrobe_id: 10)
Item.create(kind: "top", color: "green", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 2, wardrobe_id: 2)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 2, wardrobe_id: 10)

#AJ's clothes
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 3, wardrobe_id: 11)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 3, wardrobe_id: 11)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 3, wardrobe_id: 11)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 3, wardrobe_id: 3)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 3, wardrobe_id: 3)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 3, wardrobe_id: 11)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 3, wardrobe_id: 3)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 3, wardrobe_id: 11)

#jason's clothes 
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 4, wardrobe_id: 12)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 4, wardrobe_id: 12)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 4, wardrobe_id: 12)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 4, wardrobe_id: 4)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 4, wardrobe_id: 4)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 4, wardrobe_id: 12)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 4, wardrobe_id: 12)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 4, wardrobe_id: 4)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 4, wardrobe_id: 12)


#Andrew's clothes 
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 5, wardrobe_id: 13)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 5, wardrobe_id: 13)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 5, wardrobe_id: 5)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 5, wardrobe_id: 5)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 5, wardrobe_id: 13)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 5, wardrobe_id: 13)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 5, wardrobe_id: 5)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 5, wardrobe_id: 13)

#Alyssa's clothes 
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 6, wardrobe_id: 6)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 6, wardrobe_id: 6)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 6, wardrobe_id: 6)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 6, wardrobe_id: 14)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 6, wardrobe_id: 14)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 6, wardrobe_id: 6)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 6, wardrobe_id: 6)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 6, wardrobe_id: 14)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 6, wardrobe_id: 6)

#Varun's clothes
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 7, wardrobe_id: 7)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 7, wardrobe_id:15)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 7, wardrobe_id: 7)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 7, wardrobe_id:15)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 7, wardrobe_id: 7)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 7, wardrobe_id: 15)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 7, wardrobe_id: 15)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 7, wardrobe_id: 7)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 7, wardrobe_id: 7)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 7, wardrobe_id: 15)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 7, wardrobe_id: 7)

#Val's clothes
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 8, wardrobe_id:16)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 8, wardrobe_id: 8)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2015, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "bottom", color: "green", season: "winter", image_url: "", date: 2017, location: "second drawer", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "orange", season: "summer", image_url: "", date: 2019, location: "closet", size: "XL", user_id: 8, wardrobe_id:16)
Item.create(kind: "shoes", color: "yellow", season: "summer", image_url: "", date: 2014, location: "shelf", size: "XS", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "blue", season: "winter", image_url: "", date: 1997, location: "under bed storage", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "brown", season: "summer", image_url: "", date: 2012, location: "closet", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "black", season: "winter", image_url: "", date: 2017, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2013, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2016, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2002, location: "closet", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "orange", season: "summer", image_url: "", date: 2004, location: "hallway closet", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "red", season: "winter", image_url: "", date: 2009, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "purple", season: "winter", image_url: "", date: 2017, location: "bottom drawer", size: "L", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "white", season: "summer", image_url: "", date: 2019, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 2019, location: "under bed storage", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2018, location: "closet", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "orange", season: "winter", image_url: "", date: 1985, location: "second drawer", size: "L", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "yellow", season: "summer", image_url: "", date: 1990, location: "under bed storage", size: "S", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "blue", season: "winter", image_url: "", date: 2015, location: "shelf", size: "M", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "purple", season: "winter", image_url: "", date: 2018, location: "shelf", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "black", season: "winter", image_url: "", date: 2011, location: "first drawer", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 1960, location: "bottom drawer", size: "S", user_id: 8, wardrobe_id: 8)
Item.create(kind: "shoes", color: "brown", season: "winter", image_url: "", date: 1990, location: "bottom drawer", size: "L", user_id: 8, wardrobe_id: 16)
Item.create(kind: "top", color: "purple", season: "winter", image_url: "", date: 2004, location: "hallway closet", size: "XL", user_id: 8, wardrobe_id: 8)
Item.create(kind: "bottom", color: "red", season: "winter", image_url: "", date: 2019, location: "closet", size: "XS", user_id: 8, wardrobe_id: 8)
Item.create(kind: "top", color: "orange", season: "winter", image_url: "", date: 2019, location: "shelf", size: "M", user_id: 8, wardrobe_id: 16)
Item.create(kind: "bottom", color: "yellow", season: "summer", image_url: "", date: 2019, location: "shelf", size: "L", user_id: 8, wardrobe_id: 8)





puts "end seed"